name: SECOND ACTION
env:
  PROJECT_NAME: "PIPE2-${{ github.sha }}"
  OWNER: "Dima-2"

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT SECRET
        run: |
          echo "My secret value is : ${{ secrets.MYSECRET }}"
          echo "PROJECT_NAME : ${{ env.PROJECT_NAME }}"
          echo "REPO NAME : ${{ github.repository }}"
