name: SECOND ACTION
env:
  PROJECT_NAME: "PIPE2-${{ github.sha }}.zip"
  OWNER: "Dima-2"
  BUCKET_NAME: "rt-sadna-git"
  AWS_REGION: "il-central-1"

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT SECRET
        run: |
          echo "My secret value is : ${{ secrets.MYSECRET }}"
          echo "PROJECT_NAME : ${{ env.PROJECT_NAME }}"
          echo "REPO NAME : ${{ github.repository }}"
          aws --version

      - run: |
          echo " this action was triggered by ${{ github.event_name }}"
          echo " this action run on ${{ runner.os }}"

      - uses: actions/checkout@v7

      - name: Create package
        run: zip -r ${{ env.PROJECT_NAME }} ./  -x *.git*

      - run: ls -la

      - name: Config aws
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Send package
        run: aws s3 cp ${{ env.PROJECT_NAME }} s3://${{ env.BUCKET_NAME }}/
